name: 问题咨询 Question
description: 向作者咨询软件使用、配置或操作相关的问题 | Consult about software usage, configuration or operation issues

labels: ["question"]

body:
  - type: textarea
    id: problem
    attributes:
      label: 🤔 问题描述 Problem Description
    validations:
      required: true
